kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "portscan.fullname" . }}
  labels: {{- include "portscan.labels" . | nindent 4 }}
    app.kubernetes.io/component: portscan
    {{- if .Values.commonLabels }}
    {{- include "portscan.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "portscan.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "portscan.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "portscan.serviceAccountName" . }}
    namespace: {{ include "portscan.namespace" . | quote }}
