{{- if .Values.rbac.pspEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "portscan.fullname" . }}
  namespace: {{ include "portscan.namespace" . | quote }}
  labels:
    {{- include "portscan.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ tempplate "portscan.fullname" . }}
{{- end }}
